[tool.ruff]
target-version = "py310"
line-length = 100
extend-exclude = ["venv", ".venv", "build", "dist", "migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "RUF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
