[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "RUF"]
ignore = ["E501","SIM102","RUF003", "RUF002", "B904"]  # linha longa não barra; o formatter encurta quando possível

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
